name: Auth CI/CD Release

permissions:
  contents: write
  id-token: write

on:
  push:
    branches: [ "main" ]
    paths:
      - 'auth/**'
  workflow_dispatch:

jobs:
  release-auth:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v2
        with:
          node-version: '24'

      - name: Update Auth Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: cd auth && npx --package semantic-release@25 --package @semantic-release/changelog --package @semantic-release/git --package @semantic-release/exec semantic-release
