name: Auth CI/CD Test

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - 'auth/**'
  workflow_dispatch:

jobs:
  test-auth:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: cd auth && cargo build

      - name: Run Linters
        run: cd auth && cargo check && cargo clippy

      - name: Run Tests
        run: cd auth && cargo test
